name: Deploy to Azure SWA
      
env:
  skip_deploy_on_missing_secrets: true
  
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:  
    runs-on: ubuntu-latest
    name: Deploy RoshanGautam.com to Azure
    environment:
      name: azure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g @azure/static-web-apps-cli
      - run: swa build      
      - run: swa deploy -d ${{ secrets.DEPLOYMENT_TOKEN }}
