name: Azure
      
env:
  skip_deploy_on_missing_secrets: true
  
on:
  workflow_dispatch:
  push:
    branches:
      - main  
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build_and_deploy_job:  
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: azure
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v3
          with:
          node-version: 18          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "app" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
