name: Build
      
env:
  skip_deploy_on_missing_secrets: true
  
on:
  workflow_dispatch:
  pull_request:
    types: [open, update]
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest
    name: Build RoshanGautam.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g @azure/static-web-apps-cli
      - run: swa build
