name: Github Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          working-dir: app
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
