name: Github Pages

on:
  push:
    branches:
      - main  
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18      
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          working-dir: app
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
